services:
  django:
    container_name: django
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CADDY_ADMIN=http://caddy:2019

  caddy:
    container_name: caddy
    build:
      context: ./deploy
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "2019:2019"
    volumes:
      - ./deploy/Caddyfile.conf:/etc/caddy/Caddyfile  
      - ./deploy/www:/srv
    depends_on:
      - django