version: '3.9'

services:
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile