
services:
  django:
    container_name: django
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./deploy/caddy.json:/etc/caddy/caddy.json  # Volumen compartido
    expose:
      - "8000"  # Solo accesible desde otros contenedores

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    expose:
      - "80"  # Servido por Nginx, solo interno

  caddy:
    container_name: caddy
    build:
      context: ./deploy
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"  # ¡Ahora todo va por aquí!
    volumes:
      - ./deploy/caddy.json:/etc/caddy/caddy.json


