# Compilación de Caddy con plugin de rate-limit
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-ratelimit

# Imagen final
FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY caddy.json /etc/caddy/caddy.json

# Usa caddy.JSON 
CMD ["caddy", "run", "--config", "/etc/caddy/caddy.json"]





