name:  Deploy CloudGuardian

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar repositorio
        uses: actions/checkout@v3

      - name:  Iniciar sesión SSH con clave secreta
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name:  Subir proyecto al servidor
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' ./ ian@167.235.155.72:/home/ian/cloudguardian

      - name:  Ejecutar despliegue en el servidor
        run: |
          ssh ian@167.235.155.72 << 'EOF'
          cd /home/ian/cloudguardian
          docker-compose down -v
          docker system prune -f
          docker-compose build --no-cache
          docker-compose up -d
          exit
          EOF

  



